test_add_negative (python空白.class_13.TestAdd) ... ok
test_add_positive (python空白.class_13.TestAdd) ... ok
test_add_zero (python空白.class_13.TestAdd) ... FAIL

======================================================================
FAIL: test_add_zero (python空白.class_13.TestAdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\柠檬\python10期\python空白\class_13.py", line 11, in test_add_zero
    self.assertEqual(1,res)#断言函数的应用，判断前后是否一样
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1)
